# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_skill_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
