# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skill_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='likes',
            new_name='number_of_likes',
        ),
    ]
